# Generated by Django 3.1 on 2020-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='img',
            field=models.CharField(max_length=2800),
        ),
    ]
