# Generated by Django 3.1 on 2020-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20200812_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='img',
            field=models.CharField(max_length=258000),
        ),
    ]
